Create release-guide.md
mesosphere/dcos-cassandra-service pull request #262
Opened 2016-09-26 17:52 UTC by mohitsoni

2016-09-26 17:56 UTC, nickbp commented on release-guide.md
> +## Clone the repo (including sub-modules)
Can submodules comment be omitted? I thought we weren't using those anymore

2016-09-26 17:57 UTC, nickbp commented on release-guide.md
> +3. Update the universe `dcos-cassandra-service/universe` with new URL if necessary.
Can't hurt to link to the universe file here (resources.json I assume)

2016-09-26 17:57 UTC, nickbp commented on release-guide.md
> +4. Trigger this job: https://jenkins.mesosphere.com/service/jenkins/view/Infinity/job/cassandra/job/0-trigger-tag/ with the tag version created in step 3.
These could all be presented as markdown links

2016-09-26 17:58 UTC, mohitsoni commented on release-guide.md
> +## Clone the repo (including sub-modules)
Done!

2016-09-26 18:03 UTC, mohitsoni commented on release-guide.md
> +4. Trigger this job: https://jenkins.mesosphere.com/service/jenkins/view/Infinity/job/cassandra/job/0-trigger-tag/ with the tag version created in step 3.
Done!

2016-09-26 18:03 UTC, mohitsoni commented on release-guide.md
> +3. Update the universe `dcos-cassandra-service/universe` with new URL if necessary.
Done!

2016-09-26 18:06 UTC, mgummelt commented on release-guide.md
> +4. Trigger the [0-trigger-tag](https://jenkins.mesosphere.com/service/jenkins/view/Infinity/job/cassandra/job/0-trigger-tag/) job with the tag version created in step 3.
Why is this manual?  The process should just be:

1) tag
2) push
2) observe that the universe PR is created

2016-09-26 18:07 UTC, nickbp approved these changes

2016-09-26 18:07 UTC, mgummelt commented on release-guide.md
> +$ ./gradlew clean build
Why do I need to build locally for a release?  Shouldn't CI handle it?

2016-09-26 18:08 UTC, mgummelt commented on release-guide.md
> +# Release Guide
I think we should put this in our wiki instead of in Github.  This isn't relevant to non-Mesosphere contributers

2016-09-26 18:17 UTC, mohitsoni commented on release-guide.md
> +# Release Guide
I thought about it. And, figured it's better to keep everything in one-place. 

I don't mind moving this to our wiki.

2016-09-26 18:18 UTC, mohitsoni commented on release-guide.md
> +$ ./gradlew clean build
The CI job will do it anyways. Let me update it.

2016-09-26 18:27 UTC, mohitsoni commented on release-guide.md
> +4. Trigger the [0-trigger-tag](https://jenkins.mesosphere.com/service/jenkins/view/Infinity/job/cassandra/job/0-trigger-tag/) job with the tag version created in step 3.
The plumbing between `0-trigger-tag` and `release-to-universe` is missing right now. We can certainly improve it.

2016-09-28 17:13 UTC, gabrielhartmann commented
@triclambert, @mohitsoni, @mgummelt.  If this is moving to the wiki, we should close this PR.

2016-09-28 18:07 UTC, mgummelt requested changes

2016-09-28 18:07 UTC, mgummelt commented on release-guide.md
> +# Release Guide
Either is fine with me

2016-09-28 18:08 UTC, mgummelt requested changes

2016-09-28 18:08 UTC, mgummelt commented on release-guide.md
> +6. Use version from step 3 and stub universe URL from step 5 to trigger [release-to-universe](https://jenkins.mesosphere.com/service/jenkins/view/Infinity/job/infinity-tools/job/release-to-universe/)
7. Merge the Universe PR

2016-09-28 18:11 UTC, mgummelt requested changes

2016-09-28 18:11 UTC, mgummelt commented on release-guide.md
> +# Release Guide
What about releasing DSE?

2016-11-10 23:30 UTC, NimaVaziri commented
Moved this to the wiki so closing.

2016-11-10 23:30 UTC, closed without merging