Allow configurable AuthN/AuthZ
mesosphere/dcos-cassandra-service pull request #281
Opened 2016-10-10 18:35 UTC by gabrielhartmann

2016-10-10 23:54 UTC, mohitsoni requested changes

2016-10-10 23:54 UTC, mohitsoni commented on README.md
> +Further information regarding how to change authentication and authorization of a Cassaandra cluster is available [here](https://docs.datastax.com/en/cassandra/2.1/cassandra/security/security_config_
Provide links for Cassandra 3.x:
https://docs.datastax.com/en/cassandra/3.0/cassandra/configuration/secureConfigInternalAuth.html
https://docs.datastax.com/en/cassandra/3.0/cassandra/configuration/secureConfigNativeAuth.html

2016-10-10 23:58 UTC, gabrielhartmann commented on README.md
> +Further information regarding how to change authentication and authorization of a Cassaandra cluster is available [here](https://docs.datastax.com/en/cassandra/2.1/cassandra/security/security_config_
@mohitsoni: Thanks.

2016-10-11 02:54 UTC, mohitsoni approved these changes

2016-10-11 02:54 UTC, merged