Consume mesos 1.0.1
mesosphere/dcos-cassandra-service pull request #338
Opened 2016-12-07 03:37 UTC by NimaVaziri

Bumps the mesos version to 1.0.1 and updates executor to consume a specified mesos binary given a URI.

2016-12-07 03:48 UTC, verma7 commented on build.gradle
> +        mesosVer = '1.0.1'
Should this be `1.0.2`?

2016-12-07 17:48 UTC, gabrielhartmann commented on build.gradle
> +        mesosVer = '1.0.1'
Should be 1.0.2

2016-12-07 17:49 UTC, gabrielhartmann commented on cassandra-scheduler/src/test/java/com/mesosphere/dcos/cassandra/common/offer/ClusterTaskOfferRequirementProviderTest.java
>          final Protos.ExecutorInfo executorInfo = requirement.getExecutorRequirementOptional().get().getExecutorInfo();
What changed, so that the tests changed?

2016-12-07 17:51 UTC, gabrielhartmann requested changes
Compilation version is incorrect, although probably harmless.

2016-12-07 19:28 UTC, NimaVaziri commented on cassandra-scheduler/src/test/java/com/mesosphere/dcos/cassandra/common/offer/ClusterTaskOfferRequirementProviderTest.java
>          final Protos.ExecutorInfo executorInfo = requirement.getExecutorRequirementOptional().get().getExecutorInfo();
The `executorInfo` now has one more URI (the location of the libmesos bundle) so the tests needed to reflect that.

2016-12-07 19:40 UTC, NimaVaziri commented
retest this please

2016-12-08 00:26 UTC, NimaVaziri commented
retest this please

2016-12-08 18:01 UTC, NimaVaziri commented
retest this please

2016-12-08 19:30 UTC, NimaVaziri commented
retest this please

2016-12-08 21:18 UTC, NimaVaziri commented
retest this please

2016-12-08 21:24 UTC, nickbp commented
dcos-tests flakes SHOULD finally be fixed now

2016-12-08 23:32 UTC, NimaVaziri commented
retest this please

2016-12-09 01:22 UTC, NimaVaziri commented
retest this please

2016-12-09 20:45 UTC, NimaVaziri commented
rest this please

2016-12-09 20:46 UTC, NimaVaziri commented
retest this please

2016-12-10 00:55 UTC, NimaVaziri commented
retest this please

2016-12-13 17:53 UTC, NimaVaziri commented
retest this please

2016-12-14 21:50 UTC, nickbp reviewed
Duplicate `LD_LIBRARY_PATH`/`MESOS_NATIVE_JAVA_LIBRARY` settings in CassandraTaskExecutor.

2016-12-14 21:50 UTC, nickbp commented on cassandra-commons/src/main/java/com/mesosphere/dcos/cassandra/common/tasks/CassandraTaskExecutor.java
> +                        .put("LD_LIBRARY_PATH", "$MESOS_SANDBOX/libmesos-bundle/lib")
I wouldn't expect dynamic `LD_LIBRARY_PATH`/`MESOS_NATIVE_JAVA_LIBRARY` to work as envvars. Shouldn't they be `export`s in the command itself?

2016-12-14 21:50 UTC, nickbp commented on cassandra-commons/src/main/java/com/mesosphere/dcos/cassandra/common/tasks/CassandraTaskExecutor.java
> +                                .put("LD_LIBRARY_PATH", "$MESOS_SANDBOX/libmesos-bundle/lib")
I wouldn't expect dynamic `LD_LIBRARY_PATH`/`MESOS_NATIVE_JAVA_LIBRARY` to work as envvars. Shouldn't they be `export`s in the command itself?

2016-12-14 21:50 UTC, nickbp commented on cassandra-commons/src/main/java/com/mesosphere/dcos/cassandra/common/tasks/CassandraTaskExecutor.java
> +                        .put("LD_LIBRARY_PATH", "$MESOS_SANDBOX/libmesos-bundle/lib")
Looks like they can just be removed as they're already being `export`ed via scheduler.yml below?

2016-12-14 21:50 UTC, nickbp commented on cassandra-commons/src/main/java/com/mesosphere/dcos/cassandra/common/tasks/CassandraTaskExecutor.java
> +                                .put("LD_LIBRARY_PATH", "$MESOS_SANDBOX/libmesos-bundle/lib")
Looks like they can just be removed as they're already being `export`ed via scheduler.yml below.

2016-12-14 22:31 UTC, NimaVaziri commented on cassandra-commons/src/main/java/com/mesosphere/dcos/cassandra/common/tasks/CassandraTaskExecutor.java
> +                                .put("LD_LIBRARY_PATH", "$MESOS_SANDBOX/libmesos-bundle/lib")
I just reran it to confirm, seems the process env picks up the exported variables so removing these should be fine.

2016-12-14 23:06 UTC, gabrielhartmann approved these changes

2016-12-14 23:18 UTC, nickbp approved these changes

2016-12-14 23:58 UTC, merged